markdown: redcarpet
highlighter: null
permalink: /:title

url: http://ancient-rivals.com/
#baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
  
 highlighter: pygments