markdown: kramdown
highlighter: pygments
permalink: /:title

url: http://ancient-rivals.com/
#baseurl:

#redcarpet:
#  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
  
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class